### ISSUE TITLE
Errors in the script installed with the installer bat file

### ISSUE THREAD

**Issue by FrozenSoda** [Phoenix1747/fake-sandbox#4]
Error messages: https://pastebin.com/fcaKPv97

**Comment by NuclearPhoenixx** [comment]
Seems to be a pretty serious issue, I'm looking into this asap.

**Comment by NuclearPhoenixx** [comment]
Yep, seemed to be an error with quotation marks. Fixed in 1.7.2, thanks 👍

**Comment by FrozenSoda** [comment]
Thanks for fixing :) cool project btw
